name: Build Tahoe

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build App
      run: |
        xcodebuild -project Mousecape/Mousecape.xcodeproj -scheme Mousecape -configuration Release

    - name: Prepare Artifact
      run: |
        mkdir -p artifact
        cp -R Mousecape/build/Release/Mousecape.app artifact/Tahoe.app

    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: Tahoe-App
        path: artifact/Tahoe.app
